In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn.svm as skl
from scipy.io import loadmat
from sklearn.metrics import accuracy_score



import loader as ld
import regresion as rg
import numpy as np
import matplotlib.pyplot as plt
random_state = 19999

params = [0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30]

In [2]:
Ex, Ey, Vx, Vy, Px, Py = ld.carga_Numpy(random_state)

In [22]:
scores = np.zeros((len(params), len(params)))
res = list()

for v in params:
    
    for sigma in params:
        svm = skl.SVC(kernel = 'rbf', C = v, gamma = 1/(2*sigma**2))
        svm.fit(Ex, Ey)
        xpred = svm.predict(Vx)
        acertados = sum(xpred == Vy) / xpred.shape[0] * 100
        res.append(acertados)
        scores[params.index(v), params.index(sigma)] = acertados 

In [23]:
print(scores)
ind = np.where(scores == scores.max())

[[24.31506849 24.31506849 24.31506849 24.31506849 24.31506849 24.31506849
  24.31506849 24.31506849]
 [24.31506849 24.31506849 24.31506849 24.31506849 24.31506849 24.31506849
  24.31506849 24.31506849]
 [24.31506849 24.31506849 24.31506849 24.31506849 24.31506849 24.31506849
  24.31506849 24.31506849]
 [24.31506849 24.31506849 24.31506849 24.31506849 24.31506849 24.31506849
  24.31506849 29.83732877]
 [24.31506849 24.31506849 24.31506849 24.31506849 24.31506849 24.31506849
  24.31506849 55.1369863 ]
 [24.31506849 24.31506849 24.31506849 24.31506849 24.31506849 24.31506849
  24.31506849 58.21917808]
 [24.31506849 24.31506849 24.31506849 24.31506849 24.31506849 24.31506849
  24.31506849 58.21917808]
 [24.31506849 24.31506849 24.31506849 24.31506849 24.31506849 24.31506849
  24.31506849 58.21917808]]


In [ ]:
indp1 = ind[0][0]
indp2 = ind[1][0]

In [24]:
svm = skl.SVC(kernel = 'rbf', C = params[indp1], gamma = 1/(2*params[indp2]**2))
svm.fit(Ex, Ey)
print(accuracy_score(Py, svm.predict(Px)))

print("C = {} , sigma = {}".format(params[indp1],params[indp2]))

0.5826198630136986
C = 3 , sigma = 30


In [12]:
params = [10, 30, 50, 80, 100, 300]

scores = np.zeros((len(params), len(params)))
res = list()

for v in params:
    
    for sigma in params:
        svm = skl.SVC(kernel = 'rbf', C = v, gamma = 1/(2*sigma**2))
        svm.fit(Ex, Ey)
        xpred = svm.predict(Vx)
        acertados = sum(xpred == Vy) / xpred.shape[0] * 100
        res.append(acertados)
        scores[params.index(v), params.index(sigma)] = acertados
        
print(scores)
ind = np.where(scores == scores.max())

indp1 = ind[0][0]
indp2 = ind[1][0]


svm = skl.SVC(kernel = 'rbf', C = params[indp1], gamma = 1/(2*params[indp2]**2))
svm.fit(Ex, Ey)
print(accuracy_score(Py, svm.predict(Px)))

print("C = {} , sigma = {}".format(params[indp1],params[indp2]))

[[24.31506849 58.21917808 80.65068493 88.35616438 90.06849315 74.48630137]
 [24.31506849 58.21917808 80.65068493 88.27054795 89.46917808 82.44863014]
 [24.31506849 58.21917808 80.65068493 88.14212329 88.99828767 84.33219178]
 [24.31506849 58.21917808 80.65068493 88.3989726  88.78424658 86.17294521]
 [24.31506849 58.21917808 80.65068493 88.27054795 88.74143836 86.98630137]
 [24.31506849 58.21917808 80.65068493 88.27054795 88.74143836 89.34075342]]
0.8934075342465754
C = 10 , sigma = 100


In [13]:
params = [10, 50, 100, 200, 400, 500]

scores = np.zeros((len(params), len(params)))
res = list()

for v in params:
    
    for sigma in params:
        svm = skl.SVC(kernel = 'rbf', C = v, gamma = 1/(2*sigma**2))
        svm.fit(Ex, Ey)
        xpred = svm.predict(Vx)
        acertados = sum(xpred == Vy) / xpred.shape[0] * 100
        res.append(acertados)
        scores[params.index(v), params.index(sigma)] = acertados
        
print(scores)
ind = np.where(scores == scores.max())

indp1 = ind[0][0]
indp2 = ind[1][0]


svm = skl.SVC(kernel = 'rbf', C = params[indp1], gamma = 1/(2*params[indp2]**2))
svm.fit(Ex, Ey)
print(accuracy_score(Py, svm.predict(Px)))

print("C = {} , sigma = {}".format(params[indp1],params[indp2]))

[[24.31506849 80.65068493 90.06849315 84.20376712 66.22431507 57.02054795]
 [24.31506849 80.65068493 88.99828767 88.69863014 78.72431507 72.00342466]
 [24.31506849 80.65068493 88.74143836 90.19691781 82.61986301 76.96917808]
 [24.31506849 80.65068493 88.82705479 89.98287671 85.40239726 81.80650685]
 [24.31506849 80.65068493 88.74143836 90.19691781 87.37157534 84.88869863]
 [24.31506849 80.65068493 88.74143836 90.15410959 88.01369863 85.61643836]]
0.8972602739726028
C = 100 , sigma = 200


In [15]:
params = [100, 200, 1000, 2000, 5000]

scores = np.zeros((len(params), len(params)))
res = list()

for v in params:
    
    for sigma in params:
        svm = skl.SVC(kernel = 'rbf', C = v, gamma = 1/(2*sigma**2))
        svm.fit(Ex, Ey)
        xpred = svm.predict(Vx)
        acertados = sum(xpred == Vy) / xpred.shape[0] * 100
        res.append(acertados)
        scores[params.index(v), params.index(sigma)] = acertados
        
print(scores)
ind = np.where(scores == scores.max())

indp1 = ind[0][0]
indp2 = ind[1][0]


svm = skl.SVC(kernel = 'rbf', C = params[indp1], gamma = 1/(2*params[indp2]**2))
svm.fit(Ex, Ey)
print(accuracy_score(Py, svm.predict(Px)))

print("C = {} , sigma = {}".format(params[indp1],params[indp2]))

[[88.74143836 90.19691781 53.38184932 39.08390411 30.99315068]
 [88.82705479 89.98287671 59.67465753 42.25171233 32.49143836]
 [88.74143836 89.81164384 73.84417808 51.19863014 36.34417808]
 [88.74143836 89.46917808 79.45205479 55.82191781 38.05650685]
 [88.74143836 89.46917808 84.20376712 64.89726027 40.49657534]]
0.8972602739726028
C = 100 , sigma = 200


In [23]:
params = [100, 141, 175, 180]

scores = np.zeros((len(params), len(params)))
res = list()

for v in params:
    
    for sigma in params:
        svm = skl.SVC(kernel = 'rbf', C = v, gamma = 1/(2*sigma**2))
        svm.fit(Ex, Ey)
        xpred = svm.predict(Vx)
        acertados = sum(xpred == Vy) / xpred.shape[0] * 100
        res.append(acertados)
        scores[params.index(v), params.index(sigma)] = acertados
        
print(scores)
ind = np.where(scores == scores.max())

indp1 = ind[0][0]
indp2 = ind[1][0]


svm = skl.SVC(kernel = 'rbf', C = params[indp1], gamma = 1/(2*params[indp2]**2))
svm.fit(Ex, Ey)
print(accuracy_score(Py, svm.predict(Px)))

print("C = {} , sigma = {}".format(params[indp1],params[indp2]))

[[88.74143836 90.19691781 90.28253425 90.28253425]
 [88.69863014 90.19691781 89.81164384 90.02568493]
 [88.91267123 89.94006849 89.94006849 89.98287671]
 [88.91267123 89.94006849 89.94006849 89.85445205]]
0.9011130136986302
C = 100 , sigma = 175


C = 100 , sigma = 175 los mejores valores que he visto mas pequeños

In [24]:
kernels= ['rbf', 'poly', 'sigmoid']
scores = np.zeros((len(kernels)))
res = list()

for k in kernels:
    svm = skl.SVC(kernel = k, C = 100, gamma = 1/(2*175**2))
    svm.fit(Ex, Ey)
    xpred = svm.predict(Vx)
    acertados = sum(xpred == Vy) / xpred.shape[0] * 100
    print(acertados)
    res.append(acertados)
    scores[kernels.index(k)] = acertados 

90.28253424657534
51.24143835616438
19.90582191780822


In [25]:
print(scores)
ind = np.where(scores == scores.max())

[90.28253425 51.24143836 19.90582192]


In [26]:
indpk = ind[0]

In [28]:
svm = skl.SVC(kernel = 'rbf' , C = 100 , gamma = 1/(2*175**2))
svm.fit(Ex, Ey)
print(accuracy_score(Py, svm.predict(Px)))

0.9011130136986302
